// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phrruxrqhegiydwhgaih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBocnJ1eHJxaGVnaXlkd2hnYWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NjQ0MTAsImV4cCI6MjA4NjU0MDQxMH0.gdHSXmNNnWUNLNx9FAh6_f_sn1_3qGNgBvmXHpCDztI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});